# Generated by Django 2.2.6 on 2022-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20220526_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='name',
            field=models.CharField(choices=[('Taller 1', 'Taller 1'), ('Taller 2', 'Taller 2'), ('Parcial 1', 'Parcial 1'), ('Parcial 2', 'Parcial 2'), ('Parcial 3', 'Parcial 3'), ('Proyecto Final', 'Proyecto Final')], default='Internal test 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='marksclass',
            name='name',
            field=models.CharField(choices=[('Taller 1', 'Taller 1'), ('Taller 2', 'Taller 2'), ('Parcial 1', 'Parcial 1'), ('Parcial 2', 'Parcial 2'), ('Parcial 3', 'Parcial 3'), ('Proyecto Final', 'Proyecto Final')], default='Internal test 1', max_length=50),
        ),
    ]
